let mc_content={
    "ERROR_MESSAGE":"系统错误，请稍后再试",
    "PlayedMsg":"今日游戏次数已用完，\r\n请明天再来！",
    "SignOut":"注销成功。",
    "DD":"度假胜地奖赏钱",
    "OX":"小金牛",
    "redPack":" 个滨海湾金沙独家红包封",
    "ENVELOPES":"",
    "coinsCongTipsText1":"收集满500个虚拟小金牛，",
    "coinsCongTipsText2":"可获得线下金沙扭蛋机抽奖机会一次",
    "envCongTipsText1":"来自滨海湾金沙的",
    "envCongTipsText2":"滨海湾金沙独家红包封",
    "PACK":" 份",
    "amount":" 个",
    "ac_content":" 新春小金牛\r\n",
    "ad_content":" 度假胜地奖赏钱",
    "ae_content":" \r\n\r\n滨海湾金沙独家红包封",
    "MYPRIZE":"我的奖品",
    "PRIZE":"奖品",
    "tipText1":"登陆/注册保存",
    "tipText2":"您的游戏奖品和积分!",
    "MID":"会员ID:",
    "InputID":"输入您的会员ID",
    "LoginSuccess":"登陆成功",
    "FormatErr":"会员 ID\r\n格式错误",
    "NetworkErr":"系统错误\r\n请稍后再试。",
    "BinSuccess":"新记录已成功登记",
    "Binded":"奖品已经与其他会员绑定，请检查您的输入",
    "BindedBefore":"您的账号已经被绑定过了，请检查您的输入",
    "Bindfail":"绑定失败。\r\n请稍后再试。",
    "terms1":"  我希望通过信件、电邮、简讯及/或电话搜集，\r\n接收所述的最新营销动态在",
    "terms1_LBox":"此处",
    "terms2":"  我理解并同意金沙尊赏时尚会员计划的条款与条件 以及 对于本人资料的处理，同时保证声明内容    真实有效。",
    "terms2_LBox":" 本声明 ",
    "firstName":"名字",
    "lastName":"姓氏",
    "phone":"手机号码",
    "email":"电邮",
    "InvalidDate":"日期格式不正确。",
    "MIDMsg":"注册成功，会员ID为:",
    "SUFailExist":"注册失败。\r\n会员信息已存在。",
    "zpname":"请进行抽奖",
    "cText1":"小金牛",
    "cText2":"",
    "eText1":"滨海湾金沙独家红包封",
    "eText2":"",
    "eText3":"",
    "eText":"滨海湾金沙独家红包封",
    "RedeemTime":"请在2021年3月11日之前兑换您的奖品",
    "Play":"请开始游戏",
    "TC":"条款与条件。",
    "haveBinded":"你今天已经玩过了,\r\n此次游戏不会被记录",
    "ParamError":"请检查您的输入信息",
    "SUSuccess":"登陆成功:\r\n会员ID:",
    "notLogin":"会员ID：未登录",
    "confirmTxt":"会员ID:"
}