let mc_content={
    "ERROR_MESSAGE":"System is busy,\r\nplease try again later.",
    "PlayedMsg":"You have played today.\r\nPlay again tomorrow.",
    "SignOut":"Sign out success.",
    "DD":"REWARD DOLLARS",
    "OX":"OX COIN",
    "redPack":" RED PAKCET",
    "ENVELOPES":"ENVELOPES",
    "coinsCongTipsText1":"Collect 888 Virtual Ox coins to redeem a",
    "coinsCongTipsText2":"Marina Bay Sands Capsule Machine Game.",
    "envCongTipsText1":"OF MARINA BAY SANDS",
    "envCongTipsText2":"LIMITED EDITION RED PACKET ENVELOPES",
    "PACK":" PACK",
    "amount":"",
    "ac_content":" AUSPICIOUS OX\r\n COLLECTIBLE",
    "ad_content":" REWARD DOLLARS",
    "ae_content":" RED PACKET ENVELOP",
    "MYPRIZE":"MY PRIZE",
    "PRIZE":"PRIZE",
    "tipText1":"Login/Sign up to Save",
    "tipText2":"your scores & prizes!",
    "MID":"Member ID:",
    "InputID":"Input ID",
    "LoginSuccess":"Login success",
    "FormatErr":"Member ID\r\nFormat error",
    "NetworkErr":"Network Error.\r\nPlease try Again Later.",
    "BinSuccess":"Binding and Login success.",
    "Binded":"Prizes have been bound by other member.",
    "BindedBefore":"Your account have bound prizes before.",
    "Bindfail":"Binding failed.\r\nTry Again Later.",
    "terms1":"  ",
    "terms1_LBox":"here.",
    "terms2":"  I understand and agree to both the"+"Sands Rewards \r\n   LifeStyle programme terms and conditions"+" and the "+"\r\nprocessing of my personal data"+", and warrant that \r\nthe declarations "+"       "+" are true.",
    "terms2_LBox":"here",
    "firstName":"First Name",
    "lastName":"Last Name",
    "phone":"Mobile Phone",
    "email":"Email",
    "InvalidDate":"Invalid Date Format.",
    "MIDMsg":"Sin up success,patron ID:",
    "SUFailExist":"Sign up failed.\r\nPatron profile existed.",
    "zpname":"Please play the game",
    "cText1":"AUSPICIOUS OX",
    "cText2":"COLLECTIBLE",
    "eText1":"LIMITED EDITION",
    "eText2":"REDPACKET",
    "eText3":"ENVELOPES",
    "eText":"LIMITED EDITION\r\nREDPACKET\nENVELOPES",
    "RedeemTime":"Redeem your prizes by 11 March 2021",
    "Play":"Please play the game",
    "TC":"Terms and Conditions.",
    "haveBinded":"You have played today.\r\nNo new score is recorded"
}