let mc_content={
    "ERROR_MESSAGE":"System is busy,\r\nplease try again later.",
    "PlayedMsg":"You have played today.\r\nPlay again tomorrow.",
    "SignOut":"Sign out success.",
    "DD":"REWARD DOLLARS",
    "OX":"OX COINS",
    "redPack":" RED PACKET",
    "ENVELOPES":"ENVELOPES",
    "coinsCongTipsText1":"Collect 88 Virtual Ox coins ",
    "coinsCongTipsText2":"to redeem a Marina Bay Sands gift.",
    "envCongTipsText1":"OF MARINA BAY SANDS",
    "envCongTipsText2":"LIMITED EDITION RED PACKET ENVELOPES",
    "PACK":" PACK",
    "amount":"",
    "ac_content":" AUSPICIOUS OX\r\n COLLECTIBLE",
    "ad_content":" REWARD DOLLARS",
    "ae_content":" RED PACKET ENVELOP",
    "MYPRIZE":"MY PRIZES",
    "PRIZE":"PRIZES",
    "tipText1":"Login/Sign up to save",
    "tipText2":"your scores & prizes!",
    "MID":"Member ID:",
    "InputID":"Input ID",
    "LoginSuccess":"Login success",
    "FormatErr":"Member ID\r\nFormat error",
    "NetworkErr":"Network Error.\r\nPlease try Again Later.",
    "BinSuccess":"Binding and Login success.",
    "Binded":"Gifts have been bound by other member.",
    "BindedBefore":"Your account have bound prizes before.",
    "Bindfail":"Score Recorded.\r\nYour score is\r\nsuccessfully recorded.",
    "terms1":"  ",
    "terms1_LBox":"here.",
    "terms2":"  I understand and agree to both the"+" Sands Rewards \r\n   LifeStyle programme terms and conditions"+" and the "+"\r\nprocessing of my personal data"+", and warrant that \r\nthe declarations "+"       "+" are true.",
    "terms2_LBox":"here",
    "firstName":"First Name",
    "lastName":"Last Name",
    "phone":"Mobile Phone",
    "email":"Email",
    "InvalidDate":"Invalid Date Format.",
    "MIDMsg":"Sin up success,patron ID:",
    "SUFailExist":"Sign up failed.\r\nPatron profile existed.",
    "zpname":"Please play the game",
    "cText1":"EXCHANGE 88 VIRTUAL OX COINS",
    "cText2":"FOR A MARINA BAY SANDS GIFT",
    "eText1":"LIMITED EDITION",
    "eText2":"REDPACKET",
    "eText3":"ENVELOPES",
    "eText":"LIMITED EDITION\r\nREDPACKET\nENVELOPES",
    "RedeemTime":"Redeem Marina Bay Sands gifts with \r\n every 88 Ox coins by 31 March 2021.",
    "Play":"Please play the game",
    "TC":"Terms and Conditions.",
    "haveBinded":"Your Member ID was\r\nbond with another device.\r\nPlease kindly log in first.",
    "ParamError":"Please fill in\r\ncorrect information.",
    "SUSuccess":"Sign up success:\r\nMember ID:",
    "notLogin":"Please login to view.",
    "confirmTxt":"Please proceed with this \r\nSands Rewards LifeStyle ID:",
    "QRCodeContent":"Scan to follow Marina Bay Sands Wechat account\r\nfor points check and prize redemption.",
    "wechatFollow":"Follow on Wechat"
}